### ISSUE TITLE
Whitelist files/URLs on mod_evasive

### ISSUE THREAD

**Issue by nunoperalta** [shivaas/mod_evasive#13]
Hello,

As soon as I enabled this module, I noticed that a number of IPs were blocked straight away, and all of those users use Safari on iOS.

After a quick investigation, I saw that those users were requesting "serviceworker.js" several times. This is a bug and this file should only be fetched once.

I reported that bug to Apple, but unfortunately the mess is already done and many users will continue to fetch this file several times -- https://bugs.webkit.org/show_bug.cgi?id=187435

mod_evasive allows me to whitelist IPs, but is there any way I can also whitelist files, folders or subdomains so that those will not count towards DOSPageCount or DOSSiteCount?

I'm only getting alerts and blocks for those who are fetching "serviceworker.js" so much.

Thank you very much,
Nuno

**Comment by ROBERT-MCDOWELL** [comment]
No, but you can provide a patch for that....

**Comment by nunoperalta** [comment]
This is now implemented here: https://github.com/jvdmr/mod_evasive/issues/10
