### ISSUE TITLE
Apache 2.4.6 (CentOS7) - undefined symbol: evasive24_module

### ISSUE THREAD

**Issue by albansch** [shivaas/mod_evasive#14]
Hi,

I keep getting the following error once installed mod_evasive24 on Apache 2.4.6 (CentOs7):

httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 78 of /etc/httpd/conf.modules.d/00-base.conf: Can't locate API module structure `evasive24_module' in file /usr/lib64/httpd/modules/mod_evasive24.so: /usr/lib64/httpd/modules/mod_evasive24.so: undefined symbol: evasive24_module

Is there anything that needs to be tweaked? Or is it not compatible with 2.4.6?

Thx for your help.

**Comment by davemidd** [comment]
What does your LoadModule statement say?
IIRC it should be "LoadModule evasive**20**_module" - I think you might have "LoadModule evasive**24**_module"?

**Comment by albansch** [comment]
Thx for the feedback @davemidd 

I have "LoadModule evasive24_module" as per instruction on the documentation for this fork. Nevermind, closing this ticket as I actually tried to use the available mod_evasive package from EPEL repo (not this fork), hence it is not working with Apache 2.4.6.
